# Common Settings
server:
  port: 10832

spring:
  application:
    name: user-api
  profiles:
    active: prod
  jwt:
    secret: pangtudypangtudypangtudypangtudypangtudypangtudypangtudypangtudypangtudypangtudypangtudy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Redis Settings
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

# SMTP Settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: USERID
    password: USERPASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Eureka Settings
eureka:
  instance:
    instance-id: user-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://116.43.4.165:8761/eureka